min_sensor_dist: 1
self_see_default_padding: .075
self_see_links:
    - name: irb_120_link_1
    - name: irb_120_link_2
    - name: irb_120_link_3
    - name: irb_120_link_4
    - name: irb_120_link_5
    - name: irb_120_link_6
    - name: gripper_body
    - name: gripper_jaw_1
    - name: gripper_jaw_2
