abby:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 1000.0, i: 0.0, d: 100.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 1000.0, i: 0.0, d: 100.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 1000.0, i: 0.0, d: 100.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 200.0, i: 0.0, d: 50.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 100.0, i: 0.0, d: 20.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 100.0, i: 0.0, d: 20.0}
